version: "3.7"
services: 
  backend:
    container_name: backend
    build:
      context: . #esto es como la ruta, el punto significa que es en mismo lugar de este archivo
      dockerfile: Dockerfile
    ports: 
      - 3001:5001
    networks:
      - processor-net #nombre de la red
    depends_on:
      minio:
        condition: service_healthy #esto es para que espere a que minio este listo

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2021-07-12T02-44-53Z
    networks:
      - processor-net #nombre de la red
    ports:
      - 9000:9000 #esto es para que se pueda acceder desde afuera
      - 9001:9001 #esto es para que se pueda ver el dashboard
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio-volume:/data #esto es para que se guarde en el volumen
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"] #esto es para que sepa si esta vivo
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  minio-volume:

networks:
  processor-net:
    driver: bridge
  minio-network:
